/* All editable travel content comes from trip-data.json. */
'use strict';
let trip, PLACES=[], SCHEDULE=[], GROUPS={}, leafMap, markerLayer, currentMap='all';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function maps(p){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.address+' '+(p.category==='待確認'||p.name.includes('待確認')||p.name.includes('待選')?'':p.name));}
function status(p){const v=p.verification;return v?.status==='confirmed'?'<span class="status confirmed">已查核 · '+esc(v.checkedAt)+'</span>':'<span class="status">營業／店址資訊待確認</span>';}
function go(t){document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===t));document.querySelectorAll('.nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===t);b.setAttribute('aria-current',b.dataset.tab===t?'page':'false');});window.scrollTo({top:0,behavior:'instant'});if(t==='maptab')setTimeout(initMap,100);}
document.querySelectorAll('[data-tab],[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.tab||b.dataset.go)));
function renderDay(i){const d=SCHEDULE[i];document.querySelectorAll('[data-day]').forEach(b=>{b.classList.toggle('active',+b.dataset.day===i);b.setAttribute('aria-pressed',String(+b.dataset.day===i));});document.getElementById('day-content').innerHTML='<div class="day-head"><h3>'+esc(d.title)+'</h3><div>'+esc(d.subtitle)+'</div><div class="tiny">🚗 主要交通：'+esc(d.transport)+'</div></div><div class="timeline">'+d.items.map(x=>{const p=PLACES.find(p=>p.id===x.id);return '<div class="event"><div class="time">'+esc(x.time)+'</div><span class="tag '+(x.must?'pink':x.kind==='飲料'?'blue':'green')+'">'+(x.must?'⭐ 必去／必吃':esc(x.kind))+'</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.note)+'</p><div class="transport">🚶／🚗 交通建議：'+esc(x.move)+'</div>'+(p?status(p)+'<br><a class="btn" href="'+esc(maps(p))+'" target="_blank" rel="noopener noreferrer">📍 導航</a>':'')+'</div>';}).join('')+'</div><div class="callout">'+esc(d.reminder)+'</div>';}
function filtered(f){return PLACES.filter(p=>GROUPS[f].includes(p.id));}
function selectMap(f){currentMap=f;document.querySelectorAll('[data-map]').forEach(b=>{b.classList.toggle('active',b.dataset.map===f);b.setAttribute('aria-pressed',String(b.dataset.map===f));});const ps=filtered(f);if(leafMap&&markerLayer){markerLayer.clearLayers();ps.forEach(p=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return;const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({html:esc(p.emoji),className:'mapicon',iconSize:[34,34],iconAnchor:[17,17]})});marker.bindPopup('<strong>'+esc(p.emoji)+' '+esc(p.name)+'</strong><br>'+esc(p.note)+'<br>'+status(p)+'<br><a href="'+esc(maps(p))+'" target="_blank" rel="noopener noreferrer">Google Maps 導航 ↗</a>');markerLayer.addLayer(marker);});const coords=ps.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)).map(p=>[p.lat,p.lng]);if(coords.length)leafMap.fitBounds(L.latLngBounds(coords).pad(.15),{maxZoom:13});}document.getElementById('places').innerHTML=ps.map(p=>'<article class="place"><div class="em">'+esc(p.emoji)+'</div><h3>'+esc(p.name)+'</h3><span class="tag">'+esc(p.category)+'</span><p>'+esc(p.note)+'</p>'+status(p)+'<br><a class="btn alt" href="'+esc(maps(p))+'" target="_blank" rel="noopener noreferrer">導航 ↗</a></article>').join('');}
function initMap(){if(!trip)return;if(leafMap){leafMap.invalidateSize();return;}if(typeof L==='undefined'){document.getElementById('map').innerHTML='<p style="padding:24px">地圖需要網路連線載入。下方地點連結仍可使用。</p>';selectMap(currentMap);return;}document.getElementById('map').innerHTML='';leafMap=L.map('map',{scrollWheelZoom:false}).setView([23.05,120.23],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:18}).addTo(leafMap);markerLayer=L.layerGroup().addTo(leafMap);selectMap(currentMap);}
function render(){PLACES=trip.places;SCHEDULE=trip.schedule;GROUPS={all:PLACES.map(p=>p.id),...Object.fromEntries(SCHEDULE.map((d,i)=>['day'+(i+1),d.items.map(x=>x.id).filter(Boolean)])),extra:trip.extras};
document.title=trip.title+'｜2026 旅行手帳';document.getElementById('trip-title').textContent=trip.title;document.querySelector('.logo').textContent='🧳 '+trip.title;document.getElementById('trip-subtitle').textContent=trip.subtitle;document.getElementById('trip-dates').textContent=trip.dates.start.replaceAll('-','.')+' — '+trip.dates.end.replaceAll('-','.');
const dateParts=new Intl.DateTimeFormat('en-CA',{timeZone:trip.dates.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=t=>dateParts.find(p=>p.type===t).value;const today=part('year')+'-'+part('month')+'-'+part('day');const days=Math.round((Date.parse(trip.dates.start)-Date.parse(today))/86400000);document.getElementById('countdown').textContent=days>0?'出發倒數 '+days+' 天 ✨':today<=trip.dates.end?'旅行進行中 ♡':'這趟台南旅行的回憶 ♡';
const duration=Math.round((Date.parse(trip.dates.end)-Date.parse(trip.dates.start))/86400000);document.getElementById('trip-duration').textContent=(duration+1)+' 天 '+duration+' 夜';document.getElementById('trip-summary').innerHTML='<strong>旅行節奏：</strong>'+esc(trip.summary);
document.getElementById('day-tabs').innerHTML=SCHEDULE.map((d,i)=>'<button class="day-btn" data-day="'+i+'">'+esc(d.subtitle.split('｜')[0])+'<br>DAY 0'+(i+1)+'</button>').join('');document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>renderDay(+b.dataset.day)));renderDay(0);
document.getElementById('map-filters').innerHTML='<button data-map="all">全部地點</button>'+SCHEDULE.map((d,i)=>'<button data-map="day'+(i+1)+'">'+esc(d.date.slice(5).replace('-','/'))+'</button>').join('')+'<button data-map="extra">備案／伴手禮</button>';document.querySelectorAll('[data-map]').forEach(b=>b.addEventListener('click',()=>selectMap(b.dataset.map)));selectMap('all');
const hotel=PLACES.find(p=>p.id===trip.hotelId);document.querySelector('.pill.green').textContent='🏨 '+hotel.name;document.querySelector('.info small').textContent=hotel.name;
document.getElementById('transport-card').innerHTML='<h2>🚗 交通與住宿小卡</h2><p><strong>住宿：</strong>'+esc(hotel.name)+'，'+esc(trip.dates.start)+' 入住、'+esc(trip.dates.end)+' 退房，兩晚皆入住。</p>'+trip.transportNotes.map((note,i)=>'<p><strong>Day '+(i+1)+'：</strong>'+esc(note)+'</p>').join('')+'<a class="btn" href="'+esc(maps(hotel))+'" target="_blank" rel="noopener noreferrer">飯店導航 ↗</a><div class="callout"><strong>尚未定案：</strong>'+esc(trip.pendingNote)+'</div>';
document.getElementById('checklist').innerHTML=trip.checklist.map(x=>'<label><input type="checkbox" data-check="'+esc(x.id)+'"><span>'+esc(x.text)+'</span></label>').join('');document.querySelectorAll('[data-check]').forEach(input=>{const key='tainan-trip-2026-'+input.dataset.check;try{input.checked=localStorage.getItem(key)==='1';}catch{}input.addEventListener('change',()=>{try{localStorage.setItem(key,input.checked?'1':'0');}catch{}});});if(document.getElementById('maptab').classList.contains('active'))initMap();}
fetch('trip-data.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(data=>{trip=data;render();}).catch(error=>{const el=document.getElementById('load-error');el.hidden=false;el.textContent='行程資料載入失敗，請重新整理；本機預覽請以 README 的伺服器開啟，不能直接雙擊 HTML。';console.error(error);});
